// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzUVCD0E8kwLd6O4CBY7cJwglnErHWaz0',
    appId: '1:856972967049:web:8ef18f7da2411f38bb9a58',
    messagingSenderId: '856972967049',
    projectId: 'fashionshop-4f5b8',
    authDomain: 'fashionshop-4f5b8.firebaseapp.com',
    storageBucket: 'fashionshop-4f5b8.appspot.com',
    measurementId: 'G-87E17F5BM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxfNS-ypz2gwDJakp6HLaHn5bkZy1akPk',
    appId: '1:856972967049:android:da5410d3a0b3e717bb9a58',
    messagingSenderId: '856972967049',
    projectId: 'fashionshop-4f5b8',
    storageBucket: 'fashionshop-4f5b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE5xtmHcfaoK4Xvw8DVNrAkpjq6W8tyzg',
    appId: '1:856972967049:ios:764e5063d905ffb4bb9a58',
    messagingSenderId: '856972967049',
    projectId: 'fashionshop-4f5b8',
    storageBucket: 'fashionshop-4f5b8.appspot.com',
    iosBundleId: 'com.example.fashionStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE5xtmHcfaoK4Xvw8DVNrAkpjq6W8tyzg',
    appId: '1:856972967049:ios:817bd40d15e64e7abb9a58',
    messagingSenderId: '856972967049',
    projectId: 'fashionshop-4f5b8',
    storageBucket: 'fashionshop-4f5b8.appspot.com',
    iosBundleId: 'com.example.fashionStore.RunnerTests',
  );
}
